library(arules)
library(arulesViz)
movies<-read.transactions("E:\\Assignment\\Association rules\\movies.csv",format= "basket")
View(movies)
str(movies)
class(movies)
inspect(movies[1:10])
rules<-apriori(movies,parameter = list(support=0.002,confidence=0.07,minlen=3))
inspect(rules[1:10])
### Visualization####
plot(rules)
plot(rules,method = "two-key plot")
plot(rules,method = "paracoord")
plot(rules,method = "matrix3D",measure = "lift")
rules1<-apriori(movies,parameter = list(support=0.001,confidence=0.07,minlen=5))
inspect(rules1[1:10])
plot(rules1)
plot(rules1,method = "two-key plot")
plot(rules1,method = "paracoord")
plot(rules1,method = "matrix3D",measure = "lift")
##### changing the value of support and confidence###
rules2<-apriori(movies,parameter = list(support=0.003,confidence=0.06,minlen=5))
inspect(rules2[1:10])
plot(rules2)
plot(rules2,method = "two-key plot")
plot(rules2,method = "paracoord")
plot(rules2,method = "matrix3D",measure = "lift")
##### changing the value of support and confidence###
rules3<-apriori(movies,parameter = list(support=0.05,confidence=0.05,minlen=5))
inspect(rules3[1:30])
plot(rules3)
plot(rules3,method = "two-key plot")
plot(rules3,method = "paracoord")
plot(rules3,method = "matrix3D",measure = "lift")
##### changing the value of support,confidence and minimum length###
rules4<-apriori(movies,parameter = list(support=0.004,confidence=0.06,minlen=3))
inspect(rules4[1:20])
plot(rules4)
plot(rules4,method = "two-key plot")
plot(rules4,method = "paracoord")
plot(rules4,method = "matrix3D",measure = "lift")
